"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowDown, ArrowRight, ArrowUp, Download, CodeXml as Github, ContactRound as Linkedin, Mail, Copy, Check, MapPin, Code2, Layers3, Database, Cloud, Terminal, Sparkles, ShieldCheck, GitBranch, Globe2 } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { profile, projects, experience, skills } from "@/lib/portfolio";
const nav = [{id:"work",label:"Work"},{id:"experience",label:"Experience"},{id:"about",label:"About"}];

function ProjectVisual({kind}:{kind:string}) {
 if(kind==="migration")return <div className="project-visual migration-visual" aria-hidden="true"><div className="visual-top"><GitBranch size={16}/><span>MERCHANT MIGRATION</span></div><div className="migration-track"><span className="system-node">Ezetap</span><div className="track"><i/></div><div className="agent-node"><Sparkles size={22}/><small>AI workflows</small></div><div className="track"><i/></div><span className="system-node destination">Razorpay</span></div><div className="migration-result"><span><s>10 days</s><ArrowRight size={16}/><b>2 days</b></span><span className="result-pill">80% less manual effort</span></div></div>;
 if(kind==="payout")return <div className="project-visual payout-visual" aria-hidden="true"><div className="visual-top"><Layers3 size={16}/><span>GLOBAL CREATOR PAYOUTS</span></div><div className="payout-flow"><span>Calculate</span><ArrowRight/><span>Validate</span><ArrowRight/><span>Pay out</span></div><div className="payout-stats"><div><strong>25<span>%</span></strong><small>more efficient</small></div><div><strong>30<span>%</span></strong><small>fewer errors</small></div><ShieldCheck size={50}/></div></div>;
 if(kind==="checkout")return <div className="project-visual checkout-visual" aria-hidden="true"><div className="visual-top"><Globe2 size={16}/><span>MAGIC CHECKOUT</span></div><div className="checkout-display"><strong>1,500<span>+</span></strong><div>merchants enabled<br/>to sell internationally</div></div><div className="mini-tags"><span>Local pricing</span><span>Country selection</span><span>Delivery estimates</span></div></div>;
 return <div className="project-visual scale-visual" aria-hidden="true"><div className="visual-top"><Database size={16}/><span>WAREHOUSE & COMMERCE</span></div><div className="scale-display"><strong>13K</strong><span>orders / minute</span><div className="scale-icon"><Layers3 size={58}/></div></div><div className="scale-note">Asynchronous processing. Built to scale.</div></div>;
}

export default function Home(){
 const [resumeAvailable,setResumeAvailable]=useState(false);const [active,setActive]=useState("");const [copied,setCopied]=useState(false);const [copyMessage,setCopyMessage]=useState("");
 const progress=useRef<HTMLDivElement>(null);const companion=useRef<HTMLAnchorElement>(null);const heroArt=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{
  const controller=new AbortController();
  fetch("/Manish-Soni-Resume.pdf",{method:"HEAD",signal:controller.signal}).then(response=>{setResumeAvailable(response.ok && (response.headers.get("content-type")||"").includes("application/pdf"));}).catch(()=>{});
  return()=>controller.abort();
 },[]);
 useEffect(()=>{
  const reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)");let frame=0;
  const paint=()=>{frame=0;const y=window.scrollY;const max=document.documentElement.scrollHeight-window.innerHeight;
   if(progress.current)progress.current.style.transform=`scaleX(${max>0?y/max:0})`;
   if(heroArt.current)heroArt.current.style.transform=reduceMotion.matches?"none":`translate3d(0,${Math.min(y*.12,65)}px,0)`;
   if(companion.current){const visible=y>window.innerHeight*.72&&y<max-300;companion.current.dataset.visible=String(visible);companion.current.tabIndex=visible?0:-1;companion.current.setAttribute("aria-hidden",String(!visible));}
  };
  const onScroll=()=>{if(!frame)frame=requestAnimationFrame(paint);};
  const reveals=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;if(!reduceMotion.matches)entry.target.animate([{opacity:0,transform:"translateY(24px)"},{opacity:1,transform:"translateY(0)"}],{duration:650,easing:"cubic-bezier(.2,.7,.2,1)",fill:"both"});reveals.unobserve(entry.target);}),{threshold:.12});
  document.querySelectorAll("[data-reveal]").forEach(el=>reveals.observe(el));
  const sections=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setActive(entry.target.id);}),{rootMargin:"-18% 0px -50% 0px",threshold:0});
  document.querySelectorAll("main section[id]").forEach(el=>sections.observe(el));window.addEventListener("scroll",onScroll,{passive:true});window.addEventListener("resize",onScroll,{passive:true});reduceMotion.addEventListener("change",onScroll);paint();
  return()=>{window.removeEventListener("scroll",onScroll);window.removeEventListener("resize",onScroll);reduceMotion.removeEventListener("change",onScroll);cancelAnimationFrame(frame);reveals.disconnect();sections.disconnect();if(timer.current)clearTimeout(timer.current);};
 },[]);
 async function copyEmail(){try{await navigator.clipboard.writeText(profile.email);setCopied(true);setCopyMessage("Email address copied.");}catch{setCopied(false);setCopyMessage("Select and copy the email address above, or choose Email me.");}if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{setCopied(false);setCopyMessage("");},4000);}
 return <>
 <a className="skip-link" href="#main">Skip to content</a><div className="reading-progress" ref={progress} aria-hidden="true"/>
 <header className="site-header"><div className="container nav-inner"><a href="#home" className="brand" aria-label="Manish Soni, back to top"><span className="monogram">m<span>.</span></span><span>manish<span className="brand-last"> soni</span></span></a><nav aria-label="Main navigation">{nav.map(item=><a key={item.id} href={`#${item.id}`} aria-current={active===item.id?"location":undefined}>{item.label}</a>)}</nav><a className="nav-contact" href="#contact">Let’s talk <ArrowUpRight size={17}/></a></div></header>
 <main id="main">
 <section id="home" className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="tiny-square"/> BACKEND & RELIABILITY ENGINEER</div><p className="intro">Hey, I’m Manish.</p><h1>I build systems<br/>you can <span className="accent-word">count on.</span></h1><p className="hero-description">From the first API call to the last mile of production. I build scalable backends, reliable payments, and tools that make engineering better.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <ArrowDown size={18}/></a>{resumeAvailable&&<a className="button button-outline" href="/Manish-Soni-Resume.pdf" download>Resume <Download size={17}/></a>}</div><div className="hero-meta"><span><MapPin size={15}/> Bengaluru, India</span><span className="meta-divider"/><span>Currently building at <b>Razorpay</b></span></div></div><div className="hero-scene"><div className="scene-grid" aria-hidden="true"/><div className="orbit orbit-one" aria-hidden="true"/><div className="orbit orbit-two" aria-hidden="true"/><div className="scene-label"><span>01 / THE BUILDER</span><Code2 size={17}/></div><div className="hero-art" ref={heroArt}><img src="/manish-character.png" alt="An illustrated Manish, with glasses and a beard, working on his laptop" width="1254" height="1254" fetchPriority="high"/></div><div className="floating-label label-code"><Terminal size={16}/><span>build. ship. improve.</span></div><div className="floating-label label-reliability"><ShieldCheck size={17}/><span>Reliability, by design.</span></div><div className="scene-coordinate" aria-hidden="true">12.9716° N &nbsp; 77.5946° E</div></div><div className="hero-bottom"><span>GOOD ENGINEERING IS IN THE DETAILS.</span><a href="#work">Scroll to discover <ArrowDown size={14}/></a></div></section>
 <div className="company-strip"><div className="container company-inner"><p>Built with teams at</p><span className="company razorpay">Razorpay</span><span className="company pocket">pocket<span>fm</span></span><span className="company increff">INCREFF</span><span className="strip-note">Payments. Platforms. Scale.</span></div></div>
 <section id="work" className="section container"><div className="section-top" data-reveal><div><span className="eyebrow section-index">01 / SELECTED WORK</span><h2>Real problems.<br/><span className="muted-heading">Meaningful impact.</span></h2></div><p>A few things I’ve helped move<br className="desktop-break"/> from complex to working.</p></div><div className="project-grid">{projects.map((project,index)=><Dialog key={project.id}><article className={`project-card project-${project.kind}`} data-reveal><ProjectVisual kind={project.kind}/><div className="project-body"><div className="project-category"><span>{project.company} <span className="category-separator">/</span> {project.category}</span><span>0{index+1}</span></div><h3>{project.title}</h3><p>{project.summary}</p><div className="project-tags">{project.stack.map(tag=><span key={tag}>{tag}</span>)}</div><DialogTrigger asChild><button className="text-link">Explore the project <ArrowUpRight size={17}/><span className="sr-only">: {project.title}</span></button></DialogTrigger></div></article><DialogContent className="project-dialog"><span className="eyebrow">{project.company} / {project.category}</span><DialogTitle className="dialog-title">{project.title}</DialogTitle><DialogDescription className="dialog-description">{project.summary}</DialogDescription><div className="dialog-story"><h4>The challenge</h4><p>{project.challenge}</p><h4>My contribution</h4><ul>{project.contributions.map(item=><li key={item}>{item}</li>)}</ul><div className="outcome"><span>THE OUTCOME</span><p>{project.outcome}</p></div><div className="project-tags">{project.stack.map(tag=><span key={tag}>{tag}</span>)}</div><p className="project-footnote">Professional work · implementation code belongs to {project.company}.</p></div></DialogContent></Dialog>)}</div>
 <div className="side-projects" data-reveal><div className="side-projects-heading"><Code2 size={21}/><div><h3>Built out of curiosity.</h3><p>A couple of my own experiments.</p></div></div><a href="https://github.com/Maniss-ai/get-filter" target="_blank" rel="noopener noreferrer" className="side-project"><span className="project-mini-icon"><Sparkles size={20}/></span><div><h4>Get Filter <ArrowUpRight size={16}/></h4><p>Image processing · Flask, OpenCV, Kubernetes</p></div></a><a href="https://github.com/Maniss-ai/Chat_Chat_Android_App" target="_blank" rel="noopener noreferrer" className="side-project"><span className="project-mini-icon"><Layers3 size={20}/></span><div><h4>Chat Chat <ArrowUpRight size={16}/></h4><p>Real-time messaging · Android, Firebase</p></div></a></div></section>
 <section id="experience" className="experience-section"><div className="container section experience-layout"><div className="experience-intro" data-reveal><span className="eyebrow section-index">02 / THE JOURNEY</span><h2>Learning by<br/><span className="muted-heading">building.</span></h2><p>From warehouse operations to creator payouts to payment infrastructure. Every system has taught me something new.</p>{resumeAvailable&&<a className="text-link" href="/Manish-Soni-Resume.pdf" download>Download my resume <Download size={16}/></a>}</div><div className="timeline">{experience.map((job,index)=><article className="experience-item" key={job.company} data-reveal><span className={`timeline-point ${index===0?"current":""}`} aria-hidden="true"/><div className="experience-meta"><span>{job.period}</span>{index===0&&<span className="current-pill">CURRENT</span>}</div><h3>{job.company}</h3><div className="job-role">{job.role}</div><ul>{job.highlights.map(line=><li key={line}>{line}</li>)}</ul><div className="experience-tech">{job.stack}</div></article>)}</div></div></section>
 <section className="section container toolkit-section" aria-labelledby="toolkit-title"><div className="section-top" data-reveal><div><span className="eyebrow section-index">03 / MY TOOLKIT</span><h2 id="toolkit-title">The right tools.<br/><span className="muted-heading">The right trade-offs.</span></h2></div><p>Depth in backend engineering.<br className="desktop-break"/> A view of the whole system.</p></div><div className="skill-rows">{skills.map((group,i)=>{const Icon=[Code2,Layers3,Database,Cloud][i];return <div className="skill-row" data-reveal key={group.title}><div className="skill-title"><Icon size={22}/><h3>{group.title}</h3></div><div className="skill-tags">{group.items.map(item=><span key={item}>{item}</span>)}</div></div>;})}</div></section>
 <section id="about" className="section container about-section"><div className="about-portrait" data-reveal><div className="portrait-frame"><img src="/manish-character.png" alt="Illustration of Manish Soni" width="1310" height="1044" loading="lazy"/><div className="portrait-caption"><span>MANISH SONI</span><span>BENGALURU, INDIA</span></div></div><span className="photo-note">The person behind the pull requests.</span></div><div className="about-copy" data-reveal><span className="eyebrow section-index">04 / BEYOND THE CODE</span><h2>Curious by nature.<br/><span className="muted-heading">Engineer by choice.</span></h2><p>I’m a software engineer based in Bengaluru. I enjoy the work behind a simple experience: reliable APIs, thoughtful system design, and the small improvements that make a big difference in production.</p><p>I work across Java, Go, and Python, and I’m exploring how agentic AI can take repetitive work out of the engineering lifecycle.</p><div className="about-facts"><div><span className="fact-label">FOUNDATION</span><strong>B.Tech, Computer Science</strong><span>Lovely Professional University · 2019–2023</span></div><div><span className="fact-label">OUTSIDE THE EDITOR</span><strong>Two wheels. New places. New perspectives.</strong><span>Usually planning the next ride or making a travel video.</span></div></div><div className="about-socials"><a href={profile.github} target="_blank" rel="noopener noreferrer"><Github size={18}/> GitHub <ArrowUpRight size={14}/></a><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={18}/> LinkedIn <ArrowUpRight size={14}/></a></div></div></section>
 <section id="contact" className="contact-section"><div className="container contact-inner" data-reveal><span className="eyebrow section-index">05 / LET’S CONNECT</span><h2>Good things start<br/>with a <span>conversation.</span></h2><p>Have an interesting engineering challenge, an opportunity,<br className="desktop-break"/> or just want to say hello? My inbox is open.</p><div className="email-line"><a href={`mailto:${profile.email}`}>{profile.email}<ArrowUpRight/></a><button className="copy-email" onClick={copyEmail} aria-label={copied?"Email address copied":"Copy email address"}>{copied?<Check size={19}/>:<Copy size={19}/>}</button></div><div className="copy-status" role="status" aria-live="polite">{copyMessage}</div><div className="contact-actions"><a className="button button-primary" href={`mailto:${profile.email}?subject=Let%E2%80%99s%20connect`}>Email me <Mail size={18}/></a><a className="button button-outline" href={profile.linkedin} target="_blank" rel="noopener noreferrer">Connect on LinkedIn <ArrowUpRight size={18}/></a></div></div></section>
 </main><footer className="container footer"><a className="brand" href="#home"><span className="monogram">m<span>.</span></span><span>manish soni</span></a><p>Thoughtfully built. Always improving.</p><div><a href={profile.github} aria-label="Manish on GitHub" target="_blank" rel="noopener noreferrer"><Github size={19}/></a><a href={profile.linkedin} aria-label="Manish on LinkedIn" target="_blank" rel="noopener noreferrer"><Linkedin size={19}/></a><a href="#home" className="back-top" aria-label="Back to top"><ArrowUp size={19}/></a></div></footer><a ref={companion} className="scroll-companion" href="#contact" data-visible="false" tabIndex={-1} aria-hidden="true" aria-label="Say hello to Manish"><span>Let’s build something.</span><img src="/manish-character.png" width="110" height="110" alt=""/></a>
 </>;
}
