// Edit these public-safe summaries, links, skills and roles to update the site.
export const profile = { name: "Manish Soni", email: "manish.soni3872@gmail.com", linkedin: "https://www.linkedin.com/in/manishsoni/", github: "https://github.com/Maniss-ai" };
export const projects = [
 {id:"merchant-migration",kind:"migration",company:"Razorpay",category:"Developer productivity",title:"A faster path to migration.",summary:"Automating the Ezetap-to-Razorpay merchant migration with agentic AI workflows and pull request generation.",stack:["Agentic AI","Automation","Payments"],challenge:"Merchant migrations involved repetitive manual engineering work and coordination across services.",contributions:["Led the Ezetap-to-Razorpay merchant migration effort.","Applied agentic AI workflows to automate migration tasks and pull request generation.","Connected automation with the existing engineering review process."],outcome:"Reduced manual effort from 10 days to 2 days — an 80% improvement."},
 {id:"creator-payouts",kind:"payout",company:"PocketFM",category:"Financial workflows",title:"Getting creators paid, reliably.",summary:"A global UGC payout system with automated financial workflows, earnings tracking, and a stronger validation layer.",stack:["Python","Django","Apache Airflow"],challenge:"Global writer payouts needed dependable processing, earnings visibility, and fewer payment-related errors.",contributions:["Owned the UGC payout system and Django-based APIs for tracking earnings and rewards.","Orchestrated financial workflows with Apache Airflow.","Implemented validation and real-time auditing checks."],outcome:"Improved payout efficiency by 25% and reduced payment-related system errors by 30%."},
 {id:"international-checkout",kind:"checkout",company:"Razorpay",category:"Commerce infrastructure",title:"Taking checkout across borders.",summary:"Expanding Magic Checkout with market-aware pricing, merchant-specific country selection, and delivery estimates.",stack:["Microservices","REST APIs","Checkout"],challenge:"Merchants expanding internationally needed checkout behavior that reflected their supported markets and delivery options.",contributions:["Enabled international selling with dynamic market-based pricing and coupon validation.","Built country selection based on each merchant’s supported destinations.","Integrated delivery estimate APIs with fallback behavior and merchant-specific customizations."],outcome:"Enabled 1,500+ merchants to sell and deliver outside India."},
 {id:"commerce-at-scale",kind:"scale",company:"Increff",category:"Distributed systems",title:"Keeping commerce moving.",summary:"Backend systems for warehouse operations and marketplace integrations, with asynchronous processing at scale.",stack:["Java","Spring","MySQL","RabbitMQ"],challenge:"High-volume commerce requires inventory and order workflows that stay responsive as demand grows.",contributions:["Worked on backend operations supporting major e-commerce platforms.","Delivered the CRED Marketplace integration with the Assure warehouse management system.","Integrated RabbitMQ for asynchronous message processing and horizontal scalability."],outcome:"Supported systems processing 13K orders per minute, with 99.9% uptime; asynchronous messaging reduced system latency by 50%."},
];
export const experience = [
 {company:"Razorpay",period:"APR 2025 — PRESENT",role:"Software Development Engineer · Backend",highlights:["Building payment infrastructure, POS integrations, and end-to-end card payment flows across microservices.","Expanding Magic Checkout, automating merchant migrations, and building MCP integrations for engineering workflows."],stack:"Java · Go · Microservices · Payments · Agentic AI"},
 {company:"PocketFM",period:"AUG 2024 — APR 2025",role:"Software Development Engineer 1 · Backend",highlights:["Owned global creator payouts, from automated financial workflows to real-time earnings tracking.","Strengthened validation and auditing to improve payout efficiency and reduce payment-related errors."],stack:"Python · Django · Apache Airflow · APIs"},
 {company:"Increff",period:"JUN 2022 — AUG 2024",role:"Software Development Engineer · Intern to FTE",highlights:["Built and scaled backend systems for inventory, warehouse operations, and marketplace integrations.","Developed WMS and POS systems with Spring and MySQL; introduced asynchronous processing with RabbitMQ."],stack:"Java · Spring · MySQL · RabbitMQ"},
];
export const skills = [
 {title:"Languages & backend",items:["Java","Go","Python","SQL","C++","Spring Boot","Django","Flask"]},
 {title:"Systems & integration",items:["Microservices","REST APIs","RabbitMQ","Apache Airflow","Payment systems","MCP"]},
 {title:"Data & storage",items:["MySQL","PostgreSQL","Redis","ClickHouse","Firestore"]},
 {title:"Cloud & delivery",items:["Kubernetes","Docker","Jenkins","Spinnaker","Linux","Git","Agentic AI"]},
];
